### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Kishor-Kumar-Namdeo** [konvajs/vue-konva#181]
@lavrton please help me to resolve this issue,
     **Node:- 14.x
    "vue": "2.6.8",
    "vue-konva": "^2.1.7",**

/app/node_modules/konva/lib/index-node.js:1
import { Konva } from './_FullInternals.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at webpackUniversalModuleDefinition (/app/node_modules/vue-konva/umd/vue-konva.js:7:44)
    at Object. (/app/node_modules/vue-konva/umd/vue-konva.js:14:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)

**Comment by lavrton** [comment]
Try to migrate to ES modules.

**Comment by lavrton** [comment]
SHould be ok with the last konva.
