### ISSUE TITLE
vue2 - ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by MildConcussion** [konvajs/vue-konva#183]
Inertia.js just added SSR capabilities so I am trying to migrate but run into this when running from node environment:

```
/Users/rasmus/code/winefortune/node_modules/vue-konva/umd/vue-konva.js:7
		module.exports = factory(require("vue"), require("konva"));
                                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/rasmus/code/winefortune/node_modules/konva/lib/index-node.js from /Users/rasmus/code/winefortune/node_modules/vue-konva/umd/vue-konva.js not supported.
Instead change the require of index-node.js in /Users/rasmus/code/winefortune/node_modules/vue-konva/umd/vue-konva.js to a dynamic import() which is available in all CommonJS modules.
    at webpackUniversalModuleDefinition (/Users/rasmus/code/winefortune/node_modules/vue-konva/umd/vue-konva.js:7:44)
    at Object.<anonymous> (/Users/rasmus/code/winefortune/node_modules/vue-konva/umd/vue-konva.js:14:3)
    at /Users/rasmus/code/winefortune/public/js/ssr.js:1:614526
    at /Users/rasmus/code/winefortune/public/js/ssr.js:1:621932
    at Object.<anonymous> (/Users/rasmus/code/winefortune/public/js/ssr.js:1:621936) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by lavrton** [comment]
Make a demo if it still relevant.
